### ISSUE TITLE
Lista negra

### ISSUE THREAD

**Issue by cosmoscalibur** [eksperimental/qorpora#1]
A partir del listado compartido en sbosio/rla-es#24 ([gist](https://gist.github.com/eksperimental/acfc34a7bed80b967a42)), he podido identificar los siguientes lemas que no se corresponden al lenguaje español o que no son lemas bien formados.  
En la siguiente publicación la lista (con el respectivo comentario del motivo).

**Comment by cosmoscalibur** [comment]
á # Expresión islandesa
affinis # Expresión latina
ai # Expresión italiana
als # Expresión alemana
alter # Expresión latina
álter # Expresión latina: alter
amb # Expresión catalana
añ # No existe en español
ao # Expresión portuguesa
apicalis # Expresión latina
aprista # Partido político peruano
arrondissement # Expresión francesa
asi # Error de ortografía: así
auf # Expresión alemana
aurea # Error de ortografía: áureo
aureus # Expresión latina
aus # Expresión latina
australis # Expresión latina
avec # Expresión francesa
aymara # Error de ortografía: aimara
ba # Expresión china
bei # Expresión alemana
bóndi # Expresión nórdica
botanique # Expresión francesa
brasiliensis # Expresión latina
brevis # Expresión latina
br # Programación: HTML
californica # Expresión latina
canadensis # Expresión latina
canariensis # Expresión latina
cancion # Error de ortografía: canción
capella # Expresión catalana
capensis # Expresión latina
caracter # Error de ortografía: carácter
chakra # Error de ortografía: chacra
chetniks # Expresión serbia
chilensis # Expresión latina
chinensis # Expresión latina
codice # Error de ortografía: códice
coleoptera # Error de ortografía: coleóptera
coleoptero # Error de ortografía: coleóptero
coli # Expresión latina
colspan # Programación: HTML
comme # Expresión francesa
communis # Expresión latina
compañia # Error de ortografía: compañía
comune # Expresión italiana
concelho # Expresión portuguesa
concolor # Expresión inglesa
cv # Posible abreviatura: Currículum Vitae
d'agglomération # Expresión francesa
daimyo # Error de ortografía: daimio
dal # Expresión italiana
dancehall # Expresión inglesa
dans # Expresión francesa
decada # Error de ortografía: década
degli # Expresión italiana
dei # Expresión italiana
delle # Expresión italiana
dels # Expresión catalana
dem # Expresión alemana
despues # Error de ortografía: después
deux # Expresión francesa
dias # Error de ortografía: días
dieciseis # Error de ortografía: dieciséis
dió # Error de ortografía: dio
dramma # Expresión italiana
dubstep # Expresión inglesa
du # Expresión francesa
é # Expresión portuguesa
ein # Expresión alemana
elegans # Expresión latina
epoca # Error de ortografía: época
erectus # Expresión latina
estandar # Error de ortografía: estándar
estan # Error de ortografía: están
etre # Expresión francesa
eu # Expresión portuguesa
exito # Error de ortografía: éxito / Marca: Exito
fait # Expresión francesa
francais # Expresión francesa
fué # Error de ortografía: fue
für # Expresión alemana
futhark # Expresión rúnica
ga # Expresión japonesa
gángster # Error de ortografía: gánster
gracilis # Expresión latina
grandis # Expresión latina
grindcore # Expresión inglesa
habia # Error de ortografía: había
het # Expresión neerlandesa
honoris # Expresión latina
humilis # Expresión latina
ibídem # Error de ortografía: ibidem
ibidem # Expresión latina
ibn # Nombre propio: Ibn
ich # Expresión alemana
í # Expresión islandesa
il # Expresión italiana
imagenes # Error de ortografía: imágenes
indicus # Expresión latina
insignis # Expresión latina
intercepción # Error de ortografía: intersección
intercepciones # Error de ortografía: intersecciones
ios # Marca: iOS
ist # Expresión alemana
iure # Expresión latina
iuris # Expresión latina
ius # Expresión latina
jovenes # Error de ortografía: jóvenes
judoka # Error de ortografía: yudoca
karting # Expresión inglesa
kata # Error de ortografía: cata
katana # Error de ortografía: catana
kilometros # Error de ortografía: kilómetros
latin # Error de ortografía: latín
latíno # Error de ortografía: latino
legendarium # Expresión latina
lehendakari # Error de ortografía: lendakari
leur # Expresión francesa
lider # Error de ortografía: líder
li # Expresión italiana
lutea # Error de ortografía: lútea
maculatus # Expresión latina
magister # Error de ortografía: magíster
mais # Expresión portuguesa
malware # Expresión inglesa
maritima # Error de ortografía: marítima
máter # Error de ortografía: mater
mater # Expresión latina
mathbf # Programación: LaTeX
maximus # Expresión latina
mayoria # Error de ortografía: mayoría
metalcore # Expresión inglesa
mirabilis # Expresión latina
mit # Expresión alemana / Nombre propio: MIT
mixtape # Expresión inglesa
mon # Expresión francesa
mort # Expresión francesa
msnm # Abreviatura: metros sobre el nivel del mar
nach # Expresión alemana
nad # Expresión checa
nahuatl # Error de ortografía: náhuatl
nationale # Expresión francesa
nel # Expresión italiana
niger # Error de ortografía: Níger (con tilde)
noinclude # Programación
noir # Expresión francesa
nomen # Expresión latina
óblast # Expresión búlgara sin adaptar adecuadamente
occidentalis # Expresión latina
officinalis # Expresión latina
og # Expresión noruega
ókrug # Expresión bosnia sin adaptar adecuadamente
oppidum # Expresión latina
orientalis # Expresión latina
orígen # Error de ortografía: origen
ou # Expresión francesa
pais # Error de ortografía: país
paises # Error de ortografía: países
palustris # Expresión latina
pel # Expresión catalana
pelicula # Error de ortografía: película
petit # Expresión francesa
pgs # Abreviatura inglesa
piu # Expresión italiana
plantarum # Expresión latina
plc # Abreviatura inglesa
plugin # Expresión inglesa
plugins # Expresión inglesa
politica # Error de ortografía: política
powiat # Expresión polaca
princeps # Error de ortografía: prínceps
ps # Abreviatura latina
pubescens # Expresión latina
pyrenaica # Error de ortografía: pirenaica
rallyes # Expresión inglesa
ránking # Expresión inglesa mal adaptada
resinifera # Error de ortografía: resinífero
rex # Expresión latina
ri # Expresión china
robustus # Expresión latina
sa # Expresión rumana
sami # Expresión eslovena
sapiens # Expresión latina
segun # Error de ortografía: según
seiyu # Expresión japonesa
sensu # Expresión polaca
sér # Expresión islandesa
seu # Expresión portuguesa
shi # Expresión mandarín
shinigami # Expresión japonesa
similis # Expresión latina
sinensis # Expresión latina
smartphone # Expresión inglesa
sont # Expresión francesa
sp # Abreviatura latina
speciosa # Expresión latina
spinosa # Expresión latina
spp # Abreviatura latina
ssp # Abreviatura latina
stanitsa # Nombre propio de región
statu # Expresión latina
steampunk # Expresión inglesa
sua # Expresión portuguesa
subsp # Abreviatura latina
sui # Expresión italiana
sul # Expresión italiana
sylvestris # Expresión latina
synthpop # Expresión inglesa
tambien # Error de ortografía: también
tankobon # Expresión japonesa
td # Programación HTML
terra # Expresión latina
tháttr # Expresión nórdica
tí # Error de ortografía: ti
tio # Error de ortografía: tío
traves # Error de ortografía: través
tv # Abreviatura: Televisión
ua # Expresión alemana
über # Expresión alemana
uma # Expresión portuguesa
und # Expresión alemana
unico # Error de ortografía: único
ut # Expresión sueca
vias # Error de ortografía: vías
vila # Expresión portuguesa
vió # Error de ortografía: vio
viridis # Expresión latina
von # Expresión alemana
vulgaris # Expresión latina
wa # Expresión japonesa
waka # Canción
wo # Expresión alemana
zu # Expresión alemana
zur # Expresión alemana

**Comment by eksperimental** [comment]
Muchísimas gracias por la lista. Espero porder retomar este proyecto en algun momento
